In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a1 = np.array([23,45,65,43])

In [5]:
a1

array([23, 45, 65, 43])

In [6]:
a1.shape

(4,)

In [8]:
s = np.array([[23,45],[23,467]])

In [9]:
s

array([[ 23,  45],
       [ 23, 467]])

In [10]:
s.shape

(2, 2)

In [12]:
a = np.array([[1,2],[3,4]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
b = np.array([[78,90] , [22,33]])

In [15]:
b

array([[78, 90],
       [22, 33]])

In [16]:
p = np.array([[1,2,3,5],[6,7,8,9],[1,2,8,5]])

In [17]:
p

array([[1, 2, 3, 5],
       [6, 7, 8, 9],
       [1, 2, 8, 5]])

In [18]:
p.reshape(4,3)

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 1],
       [2, 8, 5]])

In [25]:
x = np.arange(25).reshape(5,5)

In [26]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
a = x.reshape(4,5)

In [24]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
x= np.arange(35).reshape(5,7)

In [29]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [30]:
x.itemsize

4

In [31]:
x.size

35

In [32]:
x.dtype

dtype('int32')

In [33]:
x.ndim

2

In [39]:
b = np.array([[1.5, 2, 3],[4, 5, 6]], dtype = 'float32')

In [40]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [41]:
ra = np.array([[34,78,89],[22,33,77]])

In [42]:
ra

array([[34, 78, 89],
       [22, 33, 77]])

In [44]:
np.zeros((3,4), dtype = 'float32')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [45]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [47]:
np.ones((2,3,4),dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [48]:
np.empty((5,5))

array([[2.75859453e-313, 1.18575755e-322, 1.14832991e-311,
        4.94065646e-324, 1.14833343e-311],
       [1.90979621e-313, 0.00000000e+000, 0.00000000e+000,
        7.90505033e-323, 1.14833343e-311],
       [1.14833343e-311, 1.14833343e-311, 4.94065646e-324,
        1.08694442e-322, 1.14833343e-311],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 4.94065646e-324],
       [9.88131292e-324, 1.14833343e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [49]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [50]:
np.arange(10,70,6)

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64])

In [53]:
np.linspace(0,2,9).reshape(3,3)

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

In [55]:
np.linspace(0,3,6).reshape(3,2)

array([[0. , 0.6],
       [1.2, 1.8],
       [2.4, 3. ]])

In [58]:
a = np.array([20,30,40,50])

In [59]:
b = np.arange(4)

In [60]:
a
b

array([0, 1, 2, 3])

In [61]:
a

array([20, 30, 40, 50])

In [62]:
b

array([0, 1, 2, 3])

In [63]:
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [64]:
c = a-b
print(c)

[20 29 38 47]


In [65]:
b**2


array([0, 1, 4, 9], dtype=int32)

In [67]:
b = np.random.random((2,3))

In [68]:
b

array([[0.3013249 , 0.01397637, 0.43081156],
       [0.82709928, 0.49812886, 0.84880283]])

In [72]:
c = np.ones((2,3))

In [73]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
d = c + b

In [75]:
d

array([[1.3013249 , 1.01397637, 1.43081156],
       [1.82709928, 1.49812886, 1.84880283]])

In [76]:
B = np.arange(3)

In [77]:
B

array([0, 1, 2])

In [78]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])